### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/wasi-wiki#3]
The following is a list of the tasks for achieving the Preview2 milestone:

 - [x] Update WASI APIs to use wit:
      - [x] wasi-clocks
      - [x] wasi-random
      - [x] wasi-filesystem
      - [x] wasi-sockets
      - [x] wasi-poll

 - [ ] Convert wasi-poll into a timers API, as poll itself will be handled by
   the canonical ABI.

 - [ ] Update `proc_exit` to a wit API.

 - [ ] Design the needed platform featuers:
      - [ ] Determine the relationship between wasi-filesystem's `descriptor`
            resource and wasi-sockets' `socket` resource. Resource subtyping?
      - [ ] Finish the design for `stream`.
      - [ ] Finish the ABI (including the `listen` and `wait` functions).

 - [ ] Implement the needed wit-bindgen features for at least C guests and Rust hosts.
      - [ ] Implement whatever we need for `descriptor` and `socket`. If we
            do resource subtyping, then also:
          - [ ] Implement wit-bindgen support for linking wit files
          - [ ] Implement wit-bindgen support for resource subtyping
      - [ ] Implement `stream`
      - [ ] Implement the async ABI in the bindings.
      - [ ] Implement profile parsing and bindings generation (TODO: work around this for now?)
      - [ ] Implement 0-level exports (TODO: work around this for now?)
      - [ ] Import imports with the `default` keyword
      - [ ] Implement wit parsing and canonical ABI for value imports/exports
      - [ ] Add a `canonical_abi_start` function, to represent the point where the component `start` is called.

 - [ ] [[Static Executable Task List]]

 - [ ] [[Library Task List]]

 - [ ] [[Dynamic Libraries Task List]]

 - [ ] Port wasi-libc (on a branch, initially)
     - [ ] Use wit-bindgen to Generate C headers from wit-bindgen.

       (I looked into using Mustang for this, but wrapping up Rust's whole
       runtime into a libc.a needs a lot more work.)

      - [ ] If we don't do resource subtyping:
          - [ ] Implement file descriptor demuxing.

    - [ ] Port the wasi-libc code to the new ABI

    - [ ] Implement the [[Typed Main]] design in the libc startup code.

    - [ ] Add a new `-mwasi-version=` option to clang and rustc to manage
      the transition.

 - [ ] Wasmtime implementation
     - [ ] Implement the new Typed Main way of running programs (see below)
     - [ ] Change how the wasmtime CLI works to be driven by wit-bindgen
     - [ ] Implement the APIs using the new wit-bindgen bindings and the
           bookkeeping plus synchronous calls implementation technique:
        - [ ] wasi-filesystem
        - [ ] wasi-clocks
        - [ ] wasi-random
        - [ ] wasi-sockets
        - [ ] wasi-poll
